/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rMyT356sckT
 */


export function Contact() {
  return (
    <>
     
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">Contact Us</h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                  We'd love to hear from you. Please fill out the form below and we'll get back to you as soon as
                  possible.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-1 lg:gap-12 xl:grid-cols-1">
              <div className="flex flex-col justify-center space-y-4 bg-white dark:bg-gray-900 p-6 rounded-lg">
                <div className="space-y-2 flex flex-col items-start">
                  <p className="text-lg font-bold tracking-tighter sm:text-xl">Name</p>
                  <input className="border-2 border-gray-300 rounded p-2 w-full" type="text" />
                  <p className="text-lg font-bold tracking-tighter sm:text-xl">Email</p>
                  <input className="border-2 border-gray-300 rounded p-2 w-full" type="email" />
                  <p className="text-lg font-bold tracking-tighter sm:text-xl">Message</p>
                  <textarea className="border-2 border-gray-300 rounded p-2 w-full" rows={5} />
                  <button className="py-2 px-4 bg-blue-500 hover:bg-blue-700 text-white font-bold rounded self-start">
                    Submit
                  </button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}



