/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aZp1YdaGeBn
 */
import Link from "next/link";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import { CardContent, Card, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function Home() {
  return (
    <>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
                  AI for Influencers
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                  Leverage AI to boost your influence. Customizable and Open
                  Source.
                </p>
              </div>
              <div className="space-x-4">
                <Link
                  className="inline-flex h-9 items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  href="#"
                >
                  Get Started
                </Link>
                <Link
                  className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300"
                  href="#"
                >
                  Learn more
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="grid items-center gap-6 lg:grid-cols-2 lg:gap-12 xl:grid-cols-2">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                    AI Features
                  </div>
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                    Harness the Power of AI
                  </h2>
                  <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                    Our AI-powered tools help influencers engage their audience,
                    predict trends, and grow their brand.
                  </p>
                </div>
                <div className="flex flex-col gap-2">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                    href="/features"
                  >
                    Learn More
                  </Link>
                </div>
              </div>
              <div className="mx-auto w-full aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last">
                <img
                  alt="AI features"
                  height="310"
                  src="/placeholder.webp"
                  style={{
                    aspectRatio: "550/310",
                    objectFit: "cover",
                  }}
                  width="550"
                />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Testimonials
              </h2>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Don't just take our word for it. See what our users have to say.
              </p>
            </div>
            <div className="grid w-full grid-cols-1 md:grid-cols-2 lg:grid-cols-3 items-center justify-center gap-8 lg:gap-12">
              <Card>
                <CardContent className="p-4">
                  <div className="text-sm leading-snug text-gray-500 dark:text-gray-400">
                    "AI Influencer Platform has revolutionized my outreach. The
                    AI-powered insights help me engage my audience better."
                  </div>
                  <div className="flex items-center gap-3 mt-4">
                    <Avatar className="h-9 w-9">
                      <AvatarImage alt="User 1" src="/placeholder-avatar.jpg" />
                      <AvatarFallback>U1</AvatarFallback>
                    </Avatar>
                    <div className="grid gap-0.5 text-xs">
                      <div className="font-medium">User 1</div>
                      <div className="text-gray-500 dark:text-gray-400">
                        Influencer
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-4">
                  <div className="text-sm leading-snug text-gray-500 dark:text-gray-400">
                    "The predictive analytics feature is a game-changer. I can
                    now plan my content strategy based on data-driven insights."
                  </div>
                  <div className="flex items-center gap-3 mt-4">
                    <Avatar className="h-9 w-9">
                      <AvatarImage alt="User 2" src="/placeholder-avatar.jpg" />
                      <AvatarFallback>U2</AvatarFallback>
                    </Avatar>
                    <div className="grid gap-0.5 text-xs">
                      <div className="font-medium">User 2</div>
                      <div className="text-gray-500 dark:text-gray-400">
                        Influencer
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-4">
                  <div className="text-sm leading-snug text-gray-500 dark:text-gray-400">
                    "AI Influencer Platform has been an integral tool in growing
                    my brand. I couldn't imagine doing what I do without it."
                  </div>
                  <div className="flex items-center gap-3 mt-4">
                    <Avatar className="h-9 w-9">
                      <AvatarImage alt="User 3" src="/placeholder-avatar.jpg" />
                      <AvatarFallback>U3</AvatarFallback>
                    </Avatar>
                    <div className="grid gap-0.5 text-xs">
                      <div className="font-medium">User 3</div>
                      <div className="text-gray-500 dark:text-gray-400">
                        Influencer
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Pricing
                </h2>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Choose the plan that's right for you. Upgrade, downgrade, or
                  cancel any time.
                </p>
              </div>
              <div className="grid w-full grid-cols-1 md:grid-cols-3 gap-8 lg:gap-12">
                <Card>
                  <CardHeader className="px-4 pt-4">
                    <h3 className="text-2xl font-bold">Basic</h3>
                  </CardHeader>
                  <CardContent className="p-4">
                    <div className="text-sm leading-snug text-gray-500 dark:text-gray-400">
                      Get started with the basic features.
                    </div>
                    <Badge className="mt-2">AI Features</Badge>
                    <Badge className="mt-2">
                      10 Predictive Analyses per month
                    </Badge>
                    <div className="mt-4 text-2xl font-bold">$9.99/mo</div>
                  </CardContent>
                  <div className="p-4">
                    <Button variant="link">Choose Plan</Button>
                  </div>
                </Card>
                <Card>
                  <CardHeader className="px-4 pt-4">
                    <h3 className="text-2xl font-bold">Pro</h3>
                  </CardHeader>
                  <CardContent className="p-4">
                    <div className="text-sm leading-snug text-gray-500 dark:text-gray-400">
                      More power for growing influencers.
                    </div>
                    <Badge className="mt-2">All Basic Features</Badge>
                    <Badge className="mt-2">
                      Unlimited Predictive Analyses
                    </Badge>
                    <Badge className="mt-2">Priority Support</Badge>
                    <div className="mt-4 text-2xl font-bold">$29.99/mo</div>
                  </CardContent>
                  <div className="p-4">
                    <Button variant="link">Choose Plan</Button>
                  </div>
                </Card>
                <Card>
                  <CardHeader className="px-4 pt-4">
                    <h3 className="text-2xl font-bold">Enterprise</h3>
                  </CardHeader>
                  <CardContent className="p-4">
                    <div className="text-sm leading-snug text-gray-500 dark:text-gray-400">
                      Custom solution for large influencers and teams.
                    </div>
                    <Badge className="mt-2">All Pro Features</Badge>
                    <Badge className="mt-2">Dedicated Account Manager</Badge>
                    <Badge className="mt-2">Custom Integrations</Badge>
                    <div className="mt-4 text-2xl font-bold">Contact Us</div>
                  </CardContent>
                  <div className="p-4">
                    <Button variant="link">Get in Touch</Button>
                  </div>
                </Card>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Contact Us
                </h2>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Have any questions? We'd love to hear from you.
                </p>
              </div>
              <form className="w-full max-w-md grid gap-4">
                <Input className="w-full" placeholder="Name" type="text" />
                <Input className="w-full" placeholder="Email" type="email" />
                <textarea className="w-full h-32" placeholder="Your Message" />
                <Button type="submit" variant="secondary">
                  Submit
                </Button>
              </form>
            </div>
          </div>
        </section>
      </main>
      
    </>
  );
}

