/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Z8fVfxW17e9
 */


export function Pricing() {
  return (
    <>
      
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center space-y-4 text-center">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl">
                  Our Pricing Plans
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                  Choose the plan that fits your needs and grow your influence with our AI tools.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-3 lg:gap-12 xl:grid-cols-3">
              <div className="flex flex-col justify-center space-y-4 bg-white dark:bg-gray-900 p-6 rounded-lg">
                <div className="space-y-2">
                  <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">Basic Plan</h2>
                  <p className="max-w-[600px] text-gray-500 md:text-lg/relaxed lg:text-base/relaxed xl:text-lg/relaxed dark:text-gray-400">
                    Get started with our basic AI tools and analytics for a lower price.
                  </p>
                  <p className="text-3xl font-bold text-green-500 dark:text-green-300">$9.99/month</p>
                </div>
              </div>
              <div className="flex flex-col justify-center space-y-4 bg-white dark:bg-gray-900 p-6 rounded-lg">
                <div className="space-y-2">
                  <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">Pro Plan</h2>
                  <p className="max-w-[600px] text-gray-500 md:text-lg/relaxed lg:text-base/relaxed xl:text-lg/relaxed dark:text-gray-400">
                    Upgrade to our Pro plan and unlock advanced AI features and priority support.
                  </p>
                  <p className="text-3xl font-bold text-green-500 dark:text-green-300">$29.99/month</p>
                </div>
              </div>
              <div className="flex flex-col justify-center space-y-4 bg-white dark:bg-gray-900 p-6 rounded-lg">
                <div className="space-y-2">
                  <h2 className="text-2xl font-bold tracking-tighter sm:text-3xl">Enterprise Plan</h2>
                  <p className="max-w-[600px] text-gray-500 md:text-lg/relaxed lg:text-base/relaxed xl:text-lg/relaxed dark:text-gray-400">
                    For large businesses and organizations, our enterprise plan offers customized solutions and
                    dedicated support.
                  </p>
                  <p className="text-3xl font-bold text-green-500 dark:text-green-300">Contact Us</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

    </>
  )
}



